spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5433/observa-acao
spring.datasource.username=postgres
spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
security.token.secret=12345678

#exposto pq to com preguiça de configurar // kkkkk coé, é pra deixar isso aqui mesmo?