spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/observa-acao
spring.datasource.username=postgres
spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
security.token.secret=12345678

# TODO: mover credenciais sensiveis para variaveis de ambiente antes de producao.
